# Generated by Django 6.0 on 2026-03-07 08:36
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_post_image'),
    ]

    operations = [
        TrigramExtension()
    ]
