# Generated by Django 6.0 on 2026-02-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='social_link',
            field=models.URLField(verbose_name='Ссылка на внешний сайт'),
        ),
    ]
