# Generated by Django 6.0 on 2026-02-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(choices=[('improve', 'Предложить улучшения'), ('article', 'Предложить статью'), ('other', 'Другое')], default='Без темы', max_length=100, verbose_name='Тема обращения'),
            preserve_default=False,
        ),
    ]
